version: '3'

tasks:
  container:
    desc: Build Container image locally
    cmds:
      - ./container-build.sh

  startenv:
    desc: Start application with environment file
    cmds:
      - node --env-file=.env build/src/main.js

  start:
    desc: Start application
    cmds:
      - node build/src/main.js

  clean:
    desc: Clean build artifacts
    cmds:
      - pnpm run clean

  build:
    desc: Build project
    deps: [lint]
    cmds:
      - pnpm run build

  watch:
    desc: Build project in watch mode
    cmds:
      - pnpm run build:watch

  release:
    desc: Build project for release
    deps: [clean]
    cmds:
      - pnpm run build:release

  lint:
    desc: Run ESLint
    cmds:
      - pnpm run lint

  # test:
  #   desc: Run tests
  #   cmds:
  #     - vitest run unit --config __tests__/vitest.config.ts

  # test:coverage:
  #   desc: Run tests with coverage
  #   cmds:
  #     - vitest run unit --config __tests__/vitest.config.ts --coverage.enabled --coverage.all

  # test:watch:
  #   desc: Run tests in watch mode
  #   cmds:
  #     - vitest unit

  prettier:
    desc: Format code with Prettier
    cmds:
      - pnpm run prettier

  check:
    desc: Check code formatting with Prettier
    cmds:
      - pnpm run prettier:check

  types:
    desc: Generate TypeScript types from Python types
    cmds:
      - pnpm run types
