name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
      - run: yarn install --frozen-lockfile
      - run: yarn run lint --if-present
      - run: yarn run prettier:check --if-present
      - run: yarn run build --if-present
